### ISSUE TITLE
Unexpected result from the Google QR web site

### ISSUE THREAD

**Issue by StephanBis** [damirkusar/AspNetCore.Totp#12]
This plugin has been running flawlessly for a year now, but since today (we just noticed it) we're getting the following error. Is there an issue with the Google QR website or does this library needs updating? Thank you in advance.

```
System.Net.Http.HttpRequestException: Unexpected result from the Google QR web site.
       ---> System.Exception: Unexpected result from the Google QR web site.
         at AspNetCore.Totp.TotpSetupGenerator.GetQrImage(String url, Int32 timeoutInSeconds)
         --- End of inner exception stack trace ---
         at AspNetCore.Totp.TotpSetupGenerator.GetQrImage(String url, Int32 timeoutInSeconds)
         at AspNetCore.Totp.TotpSetupGenerator.Generate(String issuer, String accountIdentity, String accountSecretKey, Int32 qrCodeWidth, Int32 qrCodeHeight, Boolean useHttps)
```

**Comment by hafiz-personal** [comment]
I'm also having this issue since yesterday.

**Comment by robinvanderknaap** [comment]
The Google Chart API has been deprecated since 2012 : [https://developers.google.com/chart/image/](https://developers.google.com/chart/image/). I've created a pull request (#11) a few months ago which replaces the Google Charts API.

**Comment by bob520128** [comment]
Unexpected result from the Google QR web site. facing while generating the qrcode. please help on this.
